package progettodb;
import java.awt.Component;
import java.awt.event.*;
import java.sql.*;
import javax.swing.*;
import javax.swing.text.*;
import javax.swing.JOptionPane;

public class MainWindow extends javax.swing.JFrame {

    /**
     * Creates new form MainWindow
     */
    
    public MainWindow() {
        initComponents(); 
       setLocationRelativeTo(null);
        jLabel13.setVisible(false);
        jLabel14.setVisible(false);
        jLabel15.setVisible(false);
        jLabel23.setVisible(false);
        jLabel24.setVisible(false);
        this.setVisible(true);
    }
    
    private String lastAnswer;
    private boolean inputReq = false;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ProgettoDB");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel1.setText("Punti Vita");

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jLabel2.setText("Punti Magia");

        jLabel3.setText("Zona");

        jLabel4.setText("Arma");

        jLabel6.setText("Nome");

        jLabel7.setText("-");
        jLabel7.setToolTipText("");

        jLabel8.setText("0");

        jLabel9.setText("0");

        jLabel10.setText("-");

        jLabel12.setText("-");

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/progettodb/img/guerriero1.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel13)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/progettodb/img/Green-Up-Arrow.svg.png"))); // NOI18N

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/progettodb/img/Green-Up-Arrow.svg.png"))); // NOI18N

        jLabel5.setText("stat");

        jLabel11.setText("-");

        jLabel16.setText("Nemico");

        jLabel17.setText("Nome");

        jLabel18.setText("-");

        jLabel19.setText("Punti Vita");

        jLabel20.setText("0");

        jLabel21.setText("Esperienza");

        jLabel22.setText("0");

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/progettodb/img/Green-Up-Arrow.svg.png"))); // NOI18N

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/progettodb/img/Green-Up-Arrow.svg.png"))); // NOI18N

        jLabel25.setText("Livello");

        jLabel26.setText("0");

        jLabel27.setText("Razza");

        jLabel28.setText("-");

        jLabel29.setText("Forza");

        jLabel30.setText("0");

        jLabel31.setText("(0)");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel19)
                                    .addComponent(jLabel27)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel29))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel28, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jLabel23))
                                            .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 32, Short.MAX_VALUE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel21))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel14))
                                .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel31))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel25)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addGap(14, 14, 14)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel17)
                                    .addComponent(jLabel18))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel23, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel19)
                                        .addComponent(jLabel20)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel27)
                                    .addComponent(jLabel28))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel29)
                                    .addComponent(jLabel30))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel25)
                            .addComponent(jLabel26))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel8)
                                .addComponent(jLabel1))
                            .addComponent(jLabel14))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel9)
                                .addComponent(jLabel2))
                            .addComponent(jLabel15))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel21)
                                .addComponent(jLabel22))
                            .addComponent(jLabel24))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel10)
                                .addComponent(jLabel31)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel11))
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
        if(inputReq) enterPressed();
        else jTextField2.setText(""); 
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed

    }//GEN-LAST:event_formWindowClosed

    //################# IMAGE #################
    public class Image extends Thread
    {
        private int stance = 0;
        private String classe = null;
        public Image(int stn,String cls)
        {
            stance = stn;
            classe = cls;
            jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/progettodb/img/" + classe + "1.png")));
            
        }
        
        @Override
        public void run()
        {
            jLabel13.setVisible(true);
            while(true)
            {
                while(true)
                {
                    jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/progettodb/img/" + classe + "1.png")));
                    tsleep(250);
                    if(stance == 1) dmgAniExec();
                    else if (stance == 2) healAniExec();
                    else if (stance == 3) 
                    {
                        deathAniExec();
                        break;
                    }
                    jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/progettodb/img/" + classe + "2.png")));
                    tsleep(250);
                    if(stance == 1) dmgAniExec();
                    else if (stance == 2) healAniExec();
                    else if (stance == 3) 
                    {
                        deathAniExec();
                        break;
                    }
                }
                while(stance == 3)
                {
                    jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/progettodb/img/" + classe + "6.png")));
                }
            }      
        }
        
        public void healAni()
        {
            stance = 2;
        }
        
        public void healAniExec()
        {
            jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/progettodb/img/" + classe + "4.png")));
            tsleep(200);
            jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/progettodb/img/" + classe + "1.png")));
            tsleep(200);
            jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/progettodb/img/" + classe + "4.png")));
            tsleep(200);
            jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/progettodb/img/" + classe + "1.png")));
            tsleep(100);
            stance = 0;
        }
        
        public void dmgAni()
        {
            stance = 1;
        }
        
        private void dmgAniExec()
        {
            jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/progettodb/img/" + classe + "3.png")));
            jPanel1.setLocation(jPanel1.getLocation().x-5,jPanel1.getLocation().y);
            tsleep(50);
            jPanel1.setLocation(jPanel1.getLocation().x+5,jPanel1.getLocation().y);
            tsleep(50);
            jPanel1.setLocation(jPanel1.getLocation().x-5,jPanel1.getLocation().y);
            tsleep(50);
            jPanel1.setLocation(jPanel1.getLocation().x+5,jPanel1.getLocation().y);
            tsleep(200);
            stance = 0;
        }
        
        public void deathAni()
        {
            stance = 3;
        }
        
        private void deathAniExec()
        {
            jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/progettodb/img/" + classe + "5.png")));
            tsleep(1000);
            jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/progettodb/img/" + classe + "6.png")));
        }
        
        public void restart()
        {
            stance = 0;
        }
    }
    
    //################# INTERAZIONE #################
    
    private int delay = 25;
    
    private synchronized void enterPressed() {  
        /*
        if(!isInt(jTextField2.getText()))
        {
            appendText("\n -- Inserisci un intero --");
            jTextField2.setText("");
            return;
        }
        */
        lastAnswer = jTextField2.getText();
        jTextField2.setText("");
        notifyAll();
    }
    
    public synchronized int intChoice(int min, int max)
    {
        inputReq = true;
        do
        {
            setFocusAnswer();
            try{wait();}catch (InterruptedException e){}
        }
        while(!isInt(getLastAnswer()) || Integer.parseInt(getLastAnswer())<min || Integer.parseInt(getLastAnswer())>max ||!isInt(getLastAnswer()));
        
        inputReq = false;
        return Integer.parseInt(getLastAnswer());
    }
    
    public synchronized String stringAnswer()
    {
        inputReq = true;
        do
        {
            setFocusAnswer();
            try{wait();}catch (InterruptedException e){}
        }
        while(getLastAnswer().equals(""));   
        inputReq = false;
        return getLastAnswer();
    }
    
    public String getLastAnswer()
    {
        return lastAnswer;
    }
    
    public void appendText(String text)
    {
        for (int i = 0; i<text.length(); i++)
        {
                jTextArea1.append(Character.toString(text.charAt(i)));
                jTextArea1.setCaretPosition(jTextArea1.getDocument().getLength());
                try{Thread.sleep(delay);}catch (InterruptedException e){}
        }
    }
   
    public void appendText(String text, boolean ani)
    {
        if(ani)
        {
            for (int i = 0; i<text.length(); i++)
            {
                    jTextArea1.append(Character.toString(text.charAt(i)));
                    jTextArea1.setCaretPosition(jTextArea1.getDocument().getLength());
                    try{Thread.sleep(delay);}catch (InterruptedException e){}
            }
        }
        else
        {
            jTextArea1.append(text);
            jTextArea1.setCaretPosition(jTextArea1.getDocument().getLength());
        }
    }
    
    public void clearText()
    {
        jTextArea1.setText("");
    }
    
    public void setTextDelay(int d)
    {
        delay = d;
    }
    
    public void setFocusAnswer()
    {
        jTextField2.requestFocus();
    }
    
    //################# ALTRO #################
    
    private boolean isInt(String input)
    {
        try {
            Integer.parseInt( input );
            return true;
        }
        catch( Exception e ) {
            return false;
        }
    }
    
    public void setName(String name)
    {
        jLabel7.setText(name);
    }
    
    public void setStatName(String name)
    {
        jLabel5.setText(name);
    }
    
    public void setWeapon(String name)
    {
        jLabel10.setText(name);
    }
    
    public void setWeaponDamage(int to)
    {
        jLabel31.setText("(" + to + ")");
    }
    
    public void setZone(String name)
    {
        jLabel12.setText(name);
    }
    
    public void setHP(int hp)
    {
        int diff;
        diff = Math.abs(hp-getHP());
        if(hp>getHP()) //CURA
        {
            jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/progettodb/img/Green-Up-Arrow.svg.png")));
            jLabel14.setVisible(true);
            for(int i=Integer.parseInt(jLabel8.getText()); i<=hp && hp<=100; i++)
            {
               jLabel8.setText(Integer.toString(i));
               tsleep(1495/19-(14*diff)/19);
            }
            jLabel14.setVisible(false);
            jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/progettodb/img/Green-Up-Arrow.svg.png")));
        }
        else if(hp<getHP()) //DANNO
        {
            jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/progettodb/img/Red-Down-Arrow.svg.png")));
            jLabel14.setVisible(true);
            for(int i=Integer.parseInt(jLabel8.getText()); i>=hp && hp>=0; i--)
            {
               jLabel8.setText(Integer.toString(i));
               tsleep(1495/19-(14*diff)/19);
            }
            jLabel14.setVisible(false);
            jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/progettodb/img/Red-Down-Arrow.svg.png")));
        }
        return;
    }
    
    public void setMP(int mp)
    {
        int diff;
        diff = Math.abs(mp-getMP());
        if(mp>getMP()) //RIPRISTINA
        {
            jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/progettodb/img/Green-Up-Arrow.svg.png")));
            jLabel15.setVisible(true);
            for(int i=Integer.parseInt(jLabel9.getText()); i<=mp && mp<=100; i++)
            {
               jLabel9.setText(Integer.toString(i));
               tsleep(1495/19-(14*diff)/19);
            }
            jLabel15.setVisible(false);
            jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/progettodb/img/Green-Up-Arrow.svg.png")));
        }
        else if(mp<getMP()) //CONSUMA
        {
            jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/progettodb/img/Red-Down-Arrow.svg.png")));
            jLabel15.setVisible(true);
            for(int i=Integer.parseInt(jLabel9.getText()); i>=mp && mp>=0; i--)
            {
               jLabel9.setText(Integer.toString(i));
               tsleep(1495/19-(14*diff)/19);
            }
            jLabel15.setVisible(false);
            jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/progettodb/img/Red-Down-Arrow.svg.png")));
        }
        return;
    }
    
    public void setExp(int qty, boolean scorr)
    {
        if(scorr)
        {
            jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/progettodb/img/Green-Up-Arrow.svg.png")));
            jLabel24.setVisible(true);
            for(int i=getExp(); i<=qty; i++)
            {
               jLabel22.setText(Integer.toString(i));
               tsleep(15);
            }
            jLabel24.setVisible(false);
            jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/progettodb/img/Green-Up-Arrow.svg.png")));
        }
        else
        {
            jLabel22.setText(Integer.toString(qty));
        }
    }
    
    public void setLvl(int to)
    {
        jLabel26.setText(Integer.toString(to));
    }
    
    
    public void setStat(int to)
    {
        jLabel11.setText(Integer.toString(to));
    }
    
    public void setEnemyHP(int hp)
    {
        int diff;
        diff = Math.abs(hp-getEnemyHP());
        if(hp>getEnemyHP()) //CURA
        {
            jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/progettodb/img/Green-Up-Arrow.svg.png")));
            jLabel23.setVisible(true);
            for(int i=Integer.parseInt(jLabel20.getText()); i<=hp && hp<=100; i++)
            {
               jLabel20.setText(Integer.toString(i));
               tsleep(1495/19-(14*diff)/19);
            }
            jLabel23.setVisible(false);
            jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/progettodb/img/Green-Up-Arrow.svg.png")));
        }
        else if(hp<getEnemyHP()) //DANNO
        {
            jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/progettodb/img/Red-Down-Arrow.svg.png")));
            jLabel23.setVisible(true);
            for(int i=Integer.parseInt(jLabel20.getText()); i>=hp && hp>=0; i--)
            {
               jLabel20.setText(Integer.toString(i));
               tsleep(1495/19-(14*diff)/19);
            }
            jLabel23.setVisible(false);
            jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/progettodb/img/Red-Down-Arrow.svg.png")));
        }
        return;
    }
    
    public void clearEnemy()
    {
        jLabel30.setText("0");
        jLabel28.setText("-");
        jLabel20.setText("0");
        jLabel18.setText("-");
    }
    
    public void setEnemyForza(int to)
    {
        jLabel30.setText(Integer.toString(to));
    }
    
    public void setEnemyRazza(String to)
    {
        jLabel28.setText(to);
    }
    
    public void setEnemyName(String to)
    {
        jLabel18.setText(to);
    }
    
    private int getEnemyHP()
    {
        return Integer.parseInt(jLabel20.getText());
    }
    
    private int getMP()
    {
        return Integer.parseInt(jLabel9.getText());
    }
    
    private int getExp()
    {
        return Integer.parseInt(jLabel22.getText());
    }
    
    private int getHP()
    {
        return Integer.parseInt(jLabel8.getText());
    }
    
    private String getWeapon()
    {
        return jLabel10.getText();
    }
    
    private String currentZone()
    {
        return jLabel12.getText();
    }
    
    private void tsleep(int ms)
    {
        try {
            Thread.sleep(ms);
        }
        catch(InterruptedException e) {}
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
